version: '3'

name: online-store

services:

    database:
        image: postgres:16
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./backend-fastapi/db_data:/var/lib/postgresql/data
            - ./backend-fastapi/dumps/main.sql:/docker-entrypoint-initdb.d/main.sql
            - ./backend-fastapi/dumps:/dumps


    api:
        links:
            - database
        image: api
        ports:
            - 8005:8000
        environment:
            DB_NAME: postgres
            DB_PORT: 5432
            DB_PASS: postgres
            DB_USER: postgres
            DB_HOST: database
        env_file:
            - ./backend-fastapi/.env
        build: ./backend-fastapi/api
        command: python -m uvicorn src.app:app --host 0.0.0.0 --port 8000

    
    web:
        links:
            - api
        image: web
        build: ./frontend
        command: yarn build


volumes:
    data:
        driver: local
