version: '3'

name: online-store

services:

    database:
        image: postgres:16
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./backend-fastapi/dumps/main.sql:/docker-entrypoint-initdb.d/main.sql
            - ./backend-fastapi/dumps:/dumps


    api:
        links:
            - database
        image: api
        ports:
            - 8005:8000
        environment:
            DB_NAME: postgres
            DB_PORT: 5432
            DB_PASS: postgres
            DB_USER: postgres
            DB_HOST: database
            CELERY_BROKER_URL: redis://redis:6379/0
        env_file:
            - ./backend-fastapi/.env
        build: ./backend-fastapi/api
        command: python -m uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload


    web:
        links:
            - api
        image: onlinestore
        restart: always
        ports:
            - 9000:9000
        build: ./frontend
        command: yarn dev


    redis:
        image: redis:7

    
    worker:
        links:
            - api
            - redis
        image: api
        environment:
            CELERY_BROKER_URL: redis://redis:6379/0
        env_file:
            - ./backend-fastapi/.env
        build: ./backend-fastapi/api
        command: celery -A src.worker:celery worker --loglevel info