version: '3'

name: onlinestore

services:

    web:
        links:
            - api
        image: onlinestore
        ports:
            - 9000:4000
        build: ./frontend
        command: yarn quasar serve dist/spa --port 4000
        

    database:
        image: postgres:16
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./backend/db_data:/var/lib/postgresql/data
            - ./backend/dumps/main.sql:/docker-entrypoint-initdb.d/main.sql
            - ./backend/dumps:/dumps


    api:
        links:
            - database
        image: api
        ports:
            - 8005:8000
        environment:
            DB_NAME: postgres
            DB_PORT: 5432
            DB_PASS: postgres
            DB_USER: postgres
            DB_HOST: database
            CELERY_BROKER_URL: redis://redis:6379/0
        env_file:
            - ./backend/.env
        build: ./backend/api
        command: python -m uvicorn src.app:app --host 0.0.0.0 --port 8000


    redis:
        image: redis:7

    
    worker:
        links:
            - api
            - redis
        image: api
        environment:
            CELERY_BROKER_URL: redis://redis:6379/0
        env_file:
            - ./backend/.env
        build: ./backend/api
        command: celery -A src.worker:celery worker --loglevel info

volumes:
    data:
        driver: local
