"""timestamps in order

Revision ID: 0e9944d82080
Revises: 4c17d0ef134d
Create Date: 2024-01-09 03:28:09.687640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0e9944d82080"
down_revision = "4c17d0ef134d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("create_time", sa.TIMESTAMP(), nullable=True))
    op.add_column("order", sa.Column("close_time", sa.TIMESTAMP(), nullable=True))
    op.drop_column("order", "time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column("time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    )
    op.drop_column("order", "close_time")
    op.drop_column("order", "create_time")
    # ### end Alembic commands ###
