"""order_product

Revision ID: 65193885c5da
Revises: 0e9944d82080
Create Date: 2024-01-13 17:39:21.947532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "65193885c5da"
down_revision = "0e9944d82080"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("num", sa.TEXT(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("size_id", sa.Integer(), nullable=True),
        sa.Column("color_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["color_id"],
            ["color.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["size_id"],
            ["size.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(None, "bin", "size", ["size_id"], ["id"])
    op.create_foreign_key(None, "bin", "color", ["color_id"], ["id"])
    op.drop_column("order", "color_id")
    op.drop_column("order", "size_id")
    op.drop_column("order", "product_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order", sa.Column("size_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "order", sa.Column("color_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "bin", type_="foreignkey")
    op.drop_constraint(None, "bin", type_="foreignkey")
    op.drop_table("order_product")
    # ### end Alembic commands ###
