"""add some new models

Revision ID: bc3e9c6b291a
Revises: c3ea7e348c4e
Create Date: 2024-01-07 13:15:13.762068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc3e9c6b291a"
down_revision = "c3ea7e348c4e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "city",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "color",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=True),
        sa.Column("hex_code", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "size",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pickpoint",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("sale", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bin",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_color",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("color_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["color_id"],
            ["color.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_size",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("size_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["size_id"],
            ["size.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("client", sa.Column("city", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "client", "city", ["city"], ["id"])
    op.drop_column("client", "second_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client",
        sa.Column("second_name", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "client", type_="foreignkey")
    op.drop_column("client", "city")
    op.drop_table("product_size")
    op.drop_table("product_color")
    op.drop_table("bin")
    op.drop_table("product")
    op.drop_table("pickpoint")
    op.drop_table("size")
    op.drop_table("color")
    op.drop_table("city")
    op.drop_table("category")
    # ### end Alembic commands ###
