"""init

Revision ID: c3ea7e348c4e
Revises: 
Create Date: 2023-12-24 15:57:30.576021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3ea7e348c4e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "change_pass_code_storage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.TEXT(), nullable=True),
        sa.Column("code", sa.TEXT(), nullable=True),
        sa.Column("exp_date", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "client",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.TEXT(), nullable=True),
        sa.Column("first_name", sa.TEXT(), nullable=True),
        sa.Column("email", sa.TEXT(), nullable=True),
        sa.Column("phone_number", sa.TEXT(), nullable=True),
        sa.Column("password", sa.TEXT(), nullable=True),
        sa.Column(
            "type", sa.Enum("admin", "regular_user", name="usertypes"), nullable=True
        ),
        sa.Column("gender", sa.String(length=1), nullable=True),
        sa.Column("register_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contract_storage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paid", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "photo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("obj", sa.TEXT(), nullable=True),
        sa.Column("obj_id", sa.Integer(), nullable=True),
        sa.Column("path", sa.TEXT(), nullable=True),
        sa.Column("time", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_token_storage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("refresh_token", sa.TEXT(), nullable=True),
        sa.Column("expired", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("refresh_token_storage")
    op.drop_table("photo")
    op.drop_table("contract_storage")
    op.drop_table("client")
    op.drop_table("change_pass_code_storage")
    # ### end Alembic commands ###
